// Ready-made invitation templates. Each one is a starting design (tradition, language,
// colours, crest, frame) plus sample content so it can be opened and looked at live.
import type { EventType, InviteConfig } from "./types";
import { PRESETS, defaultConfig } from "./themes";
import { fromLocalInput } from "./format";

export type Template = {
  key: string;
  name: string; // "Kasavu morning"
  blurb: string;
  caption: string; // "Kerala Hindu · Malayalam"
  group: "wedding" | "engagement" | "housewarming" | "birthday" | "corporate" | "celebration";
  type: EventType;
  tradition: string;
  language: string;
  timezone: string;
  preset: string; // key into PRESETS
  crest: string;
  headline?: string; // "invite you to the baptism of"
  eyebrow?: string;
  scheduleTitles?: string[]; // the ceremonies this template starts with
  frame: boolean;
  photo?: "none" | "blue-gold" | "green-leaves" | "pink-roses" | "white-paper" | "botanical-paper";
  layout?: "invitation" | "website";
  titleStyle?: "default" | "stacked";
  watercolor?: "none" | "aqua" | "rose" | "lilac" | "sage" | "gold";
  bigAmpersand?: boolean;
  scene?: "none" | "moonlight" | "sunrise-journey" | "golden-hour" | "garden-day" | "ocean-dusk";
  background?: "flat" | "mist" | "blush" | "dusk" | "sage";
  dateStyle?: "stacked" | "split" | "numeric";
  ornament: "none" | "floral" | "mandala" | "leaves" | "rings" | "paisley" | "garland" | "lanterns" | "arch" | "garden" | "wildflower";
  sample: {
    name1: string;
    name2: string;
    subline?: string;
    eyebrow?: string;
    city: string;
    venue: string;
    address: string;
    story: string;
    date: string; // yyyy-mm-dd
    tickets?: boolean;
  };
};

export const TEMPLATES: Template[] = [
  {
    key: "kerala-hindu",
    name: "Kasavu morning",
    blurb: "Cream and antique gold, set in Malayalam. Made for a Kerala Hindu wedding.",
    caption: "Kerala Hindu · Malayalam",
    group: "wedding",
    type: "wedding",
    tradition: "hindu-kerala",
    language: "ml",
    timezone: "Asia/Kolkata",
    preset: "kasavu",
    crest: "",
    frame: true,
    ornament: "garland",
    sample: { name1: "ലക്ഷ്മി", name2: "അരുൺ", city: "Kochi", venue: "Bolgatty Palace", address: "Mulavukad, Kochi", story: "We met at a friend's wedding and have been talking ever since.", date: "2027-01-14" },
  },
  {
    key: "garden-mandap",
    name: "Garden mandap",
    blurb: "A painted mint-to-blush sky, flowers hanging from the top, and a mandap with drapes at the foot. Script names.",
    caption: "Hindu wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "mist",
    crest: "",
    frame: false,
    background: "mist",
    dateStyle: "split",
    ornament: "garden",
    sample: { name1: "Aarav", name2: "Diya", city: "Jaipur", venue: "Rambagh Palace Gardens", address: "Bhawani Singh Road, Jaipur", story: "Two families, one long garden party, and a promise made under the marigolds.", date: "2027-02-17" },
  },
  {
    key: "wildflower",
    name: "Wildflower garden",
    blurb: "Hand-drawn wildflowers climbing both sides, a gold flourish top and bottom, script names over spaced capitals.",
    caption: "Wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "christian",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "wild",
    crest: "",
    frame: true,
    dateStyle: "stacked",
    ornament: "wildflower",
    sample: { name1: "Richard", name2: "Amanda", city: "Kochi", venue: "The Garden Terrace", address: "Fort Kochi", story: "Two families, one long friendship, and a wedding in a garden.", date: "2027-10-20" },
  },
  {
    key: "nikah",
    name: "Emerald nikah",
    blurb: "Deep emerald and gold in Arabic, laid out right-to-left with the Bismillah above the names.",
    caption: "Nikah · Arabic",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "ar",
    timezone: "Asia/Dubai",
    preset: "emerald",
    crest: "بسم الله",
    frame: true,
    ornament: "arch",
    sample: { name1: "آمنة", name2: "يوسف", city: "Dubai", venue: "Al Habtoor Palace", address: "Business Bay, Dubai", story: "بارك الله لكما وبارك عليكما وجمع بينكما في خير.", date: "2027-03-06" },
  },
  {
    key: "church",
    name: "Cathedral cream",
    blurb: "Ivory with navy type and a quiet cross. A church wedding in English.",
    caption: "Church wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "christian",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "cathedral",
    crest: "✝",
    frame: true,
    ornament: "leaves",
    sample: { name1: "Anna", name2: "Joseph", city: "Kottayam", venue: "St. Mary's Church", address: "Kanjikuzhy, Kottayam", story: "Two families, one long friendship, and a wedding we are thrilled to share with you.", date: "2027-02-20" },
  },
  {
    key: "anand-karaj",
    name: "Indigo & saffron",
    blurb: "Deep indigo with saffron accents, set in Punjabi (Gurmukhi) with the Ik Onkar above the names.",
    caption: "Anand Karaj · Punjabi",
    group: "wedding",
    type: "wedding",
    tradition: "sikh",
    language: "pa",
    timezone: "Asia/Kolkata",
    preset: "anand",
    crest: "ੴ",
    frame: true,
    ornament: "paisley",
    sample: { name1: "ਸਿਮਰਨ", name2: "ਹਰਜੀਤ", city: "Amritsar", venue: "Gurdwara Sahib", address: "Model Town, Amritsar", story: "With the blessings of Waheguru and our families, we begin our life together.", date: "2026-12-12" },
  },
  {
    key: "tamil-wedding",
    name: "Peach sunset",
    blurb: "Warm peach and terracotta in Tamil. A traditional Tamil Hindu wedding.",
    caption: "Tamil wedding · Tamil",
    group: "wedding",
    type: "wedding",
    tradition: "hindu-tamil",
    language: "ta",
    timezone: "Asia/Kolkata",
    preset: "sunset",
    crest: "ॐ",
    frame: false,
    ornament: "garland",
    sample: { name1: "மீனா", name2: "கார்த்திக்", city: "Chennai", venue: "Sri Kalyana Mandapam", address: "T. Nagar, Chennai", story: "இரு குடும்பங்களின் ஆசீர்வாதத்துடன் எங்கள் புதிய வாழ்க்கையைத் தொடங்குகிறோம்.", date: "2027-02-07" },
  },
  {
    key: "civil",
    name: "Sage garden",
    blurb: "Soft sage and ivory. A calm, modern ceremony with no religious symbols.",
    caption: "Civil ceremony · English",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Europe/London",
    preset: "sage",
    crest: "✦",
    frame: false,
    ornament: "leaves",
    sample: { name1: "Maya", name2: "Tom", city: "London", venue: "The Orangery", address: "Holland Park, London", story: "We would love you to be there when we say the words out loud.", date: "2027-05-09" },
  },
  {
    key: "engagement",
    name: "Ivory & rose",
    blurb: "Blush and ivory for an engagement evening.",
    caption: "Engagement · English",
    group: "engagement",
    type: "engagement",
    tradition: "",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "rose",
    crest: "❀",
    frame: true,
    ornament: "rings",
    sample: { name1: "Sara", name2: "Neil", city: "Bengaluru", venue: "The Leela Palace", address: "Old Airport Road, Bengaluru", story: "He asked, she said yes, and now we would like you there to celebrate.", date: "2027-01-30" },
  },
  {
    key: "gruhapravesh",
    name: "Terracotta home",
    blurb: "Warm terracotta in Hindi for a Griha Pravesh, the blessing of a new home.",
    caption: "Gruhapravesh · Hindi",
    group: "housewarming",
    type: "housewarming",
    tradition: "housewarming-hindu",
    language: "hi",
    timezone: "Asia/Kolkata",
    preset: "terracotta",
    crest: "गृह प्रवेश",
    frame: true,
    ornament: "lanterns",
    sample: { name1: "प्रिया और रोहन", name2: "", city: "Pune", venue: "Our new home", address: "Baner, Pune", story: "हमारे नए घर में आपका स्वागत है।", date: "2027-01-03" },
  },
  {
    key: "birthday",
    name: "Confetti",
    blurb: "Cream with a coral accent. A first birthday, or any birthday.",
    caption: "First birthday · English",
    group: "birthday",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "confetti",
    crest: "✦",
    frame: false,
    ornament: "lanterns",
    sample: { name1: "Kiaan", name2: "", subline: "turns one", city: "Kochi", venue: "The Garden Room", address: "Panampilly Nagar, Kochi", story: "Cake, balloons and a lot of clapping. Come and be part of it.", date: "2026-11-08" },
  },
  {
    key: "partners-dinner",
    name: "Slate dinner",
    blurb: "Restrained slate and blue for a corporate dinner. Guests get a QR pass for the door.",
    caption: "Partners' dinner · English",
    group: "corporate",
    type: "corporate",
    tradition: "corporate",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "slate",
    crest: "",
    frame: false,
    ornament: "none",
    sample: { name1: "Kerala Partners Dinner", name2: "", subline: "Annual partner evening", city: "Kochi", venue: "Grand Hyatt", address: "Bolgatty Island, Kochi", story: "An evening to thank the partners who made this year possible.", date: "2026-11-28", tickets: true },
  },
  {
    key: "jain-wedding",
    name: "Saffron mandala",
    blurb: "Warm saffron and cream with a mandala, for a Jain wedding in Hindi.",
    caption: "Jain wedding · Hindi",
    group: "wedding",
    type: "wedding",
    tradition: "jain",
    language: "hi",
    timezone: "Asia/Kolkata",
    preset: "saffron",
    crest: "",
    frame: true,
    ornament: "mandala",
    sample: { name1: "अंकित", name2: "श्रेया", city: "Indore", venue: "Mahavir Bhawan", address: "Rajwada, Indore", story: "दोनों परिवारों के आशीर्वाद से हम नए जीवन की शुरुआत कर रहे हैं।", date: "2027-02-11" },
  },
  {
    key: "buddhist-wedding",
    name: "Lotus lagoon",
    blurb: "Deep lagoon teal with brass and a lotus, for a Buddhist ceremony.",
    caption: "Buddhist wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "buddhist",
    language: "en",
    timezone: "Asia/Colombo",
    preset: "lagoon",
    crest: "☸",
    frame: true,
    ornament: "floral",
    sample: { name1: "Nimal", name2: "Tara", city: "Colombo", venue: "Temple Garden", address: "Kotte Road, Colombo", story: "May our marriage be filled with kindness, patience and joy.", date: "2027-04-10" },
  },
  {
    key: "jewish-wedding",
    name: "Blue chuppah",
    blurb: "Midnight blue with silver and a Star of David under an arch. Hebrew script.",
    caption: "Jewish wedding · Hebrew",
    group: "wedding",
    type: "wedding",
    tradition: "jewish",
    language: "he",
    timezone: "Asia/Jerusalem",
    preset: "monsoon",
    crest: "✡",
    frame: true,
    ornament: "arch",
    sample: { name1: "שרה", name2: "דניאל", city: "Jerusalem", venue: "Garden Hall", address: "Emek Refaim, Jerusalem", story: "מזל טוב", date: "2027-05-25" },
  },
  {
    key: "parsi-wedding",
    name: "Rose ivory",
    blurb: "Ivory and rose with a leaf sprig, for a Parsi wedding.",
    caption: "Parsi wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "parsi",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "rose",
    crest: "❀",
    frame: true,
    ornament: "leaves",
    sample: { name1: "Roshan", name2: "Farah", city: "Mumbai", venue: "Cama Baug", address: "Fort, Mumbai", story: "With the blessings of Ahura Mazda and our families.", date: "2027-01-23" },
  },
  {
    key: "syrian-christian",
    name: "Cream and gold",
    blurb: "Cream and antique gold with a cross, in Malayalam, for a Kerala Christian wedding.",
    caption: "Christian wedding · Malayalam",
    group: "wedding",
    type: "wedding",
    tradition: "syrian-christian",
    language: "ml",
    timezone: "Asia/Kolkata",
    preset: "kasavu",
    crest: "✝",
    frame: true,
    ornament: "leaves",
    sample: { name1: "അന്ന", name2: "ജോസഫ്", city: "Kottayam", venue: "St. Thomas Church", address: "Pala, Kottayam", story: "ദൈവത്തിന്റെ അനുഗ്രഹത്തോടെ ഞങ്ങൾ ഒന്നാകുന്നു.", date: "2027-04-17" },
  },
  {
    key: "telugu-wedding",
    name: "Marigold garland",
    blurb: "Saffron and cream with a marigold garland, set in Telugu.",
    caption: "Telugu wedding · Telugu",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "te",
    timezone: "Asia/Kolkata",
    preset: "saffron",
    crest: "ॐ",
    frame: false,
    background: "blush",
    ornament: "garland",
    sample: { name1: "సాయి", name2: "అనన్య", city: "Hyderabad", venue: "Kalyana Mandapam", address: "Jubilee Hills, Hyderabad", story: "ఇద్దరి కుటుంబాల ఆశీర్వాదంతో మా కొత్త జీవితం ప్రారంభమవుతోంది.", date: "2027-03-14" },
  },
  {
    key: "kannada-wedding",
    name: "Terracotta lanterns",
    blurb: "Terracotta and cream with hanging lanterns, in Kannada.",
    caption: "Kannada wedding · Kannada",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "kn",
    timezone: "Asia/Kolkata",
    preset: "terracotta",
    crest: "ॐ",
    frame: true,
    ornament: "lanterns",
    sample: { name1: "ಅರ್ಜುನ್", name2: "ಮೇಘನಾ", city: "Mysuru", venue: "Palace Grounds", address: "Mysuru", story: "ಎರಡೂ ಕುಟುಂಬಗಳ ಆಶೀರ್ವಾದದೊಂದಿಗೆ ನಮ್ಮ ಹೊಸ ಜೀವನ ಆರಂಭವಾಗುತ್ತಿದೆ.", date: "2027-02-27" },
  },
  {
    key: "urdu-nikah",
    name: "Emerald arch",
    blurb: "Emerald and gold under a cusped arch, laid out right-to-left in Urdu.",
    caption: "Nikah · Urdu",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "ur",
    timezone: "Asia/Karachi",
    preset: "emerald",
    crest: "بسم اللہ",
    frame: true,
    ornament: "arch",
    sample: { name1: "عائشہ", name2: "علی", city: "Lahore", venue: "Shalimar Hall", address: "Gulberg, Lahore", story: "اللہ آپ دونوں کو خوش رکھے۔", date: "2027-03-20" },
  },
  {
    key: "walima",
    name: "Lagoon reception",
    blurb: "Cool teal, brass and a soft sage sky for a Walima reception.",
    caption: "Walima · English",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "en",
    timezone: "Asia/Dubai",
    preset: "lagoon",
    crest: "",
    frame: false,
    background: "sage",
    ornament: "mandala",
    sample: { name1: "Zainab", name2: "Omar", city: "Dubai", venue: "Jumeirah Ballroom", address: "Jumeirah Beach Road, Dubai", story: "Join us for an evening of food, family and dua.", date: "2027-03-21" },
  },
  {
    key: "mehendi-sangeet",
    name: "Lavender paisley",
    blurb: "A blush-to-lavender sky with paisley, for a mehendi and sangeet evening.",
    caption: "Mehendi & Sangeet · Hindi",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "hi",
    timezone: "Asia/Kolkata",
    preset: "lavender",
    crest: "",
    frame: false,
    background: "blush",
    dateStyle: "split",
    ornament: "paisley",
    sample: { name1: "प्रिया", name2: "रोहन", city: "Delhi", venue: "The Farmhouse", address: "Chhatarpur, Delhi", story: "नाच, गाना, मेहंदी और बहुत सारा प्यार।", date: "2027-02-05" },
  },
  {
    key: "housewarming-english",
    name: "Sage house",
    blurb: "Soft sage with leaves, for a house blessing or open house.",
    caption: "Housewarming · English",
    group: "housewarming",
    type: "housewarming",
    tradition: "housewarming",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "sage",
    crest: "",
    frame: false,
    background: "sage",
    ornament: "leaves",
    sample: { name1: "The Menons", name2: "", city: "Kochi", venue: "Our new home", address: "Panampilly Nagar, Kochi", story: "Come and bless the house, and stay for lunch.", date: "2027-01-16" },
  },
  {
    key: "kids-birthday",
    name: "Blush balloons",
    blurb: "A blush sky with lanterns. For a child's birthday.",
    caption: "Kids birthday · English",
    group: "birthday",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "sunset",
    crest: "✦",
    frame: false,
    background: "blush",
    ornament: "lanterns",
    sample: { name1: "Meera", name2: "", subline: "turns five", city: "Bengaluru", venue: "Play Barn", address: "Indiranagar, Bengaluru", story: "Cake, games and a lot of glitter.", date: "2026-12-06" },
  },
  {
    key: "adult-birthday",
    name: "Midnight thirty",
    blurb: "Dusk gradient with silver. A grown-up birthday party.",
    caption: "Birthday · English",
    group: "birthday",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "noir",
    crest: "✦",
    frame: false,
    background: "dusk",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Nikhil", name2: "", subline: "turns thirty", city: "Mumbai", venue: "The Terrace", address: "Bandra, Mumbai", story: "Drinks, dinner and one very loud playlist.", date: "2026-12-19" },
  },
  {
    key: "conference",
    name: "Slate summit",
    blurb: "Restrained slate for a conference or launch. Guests get a QR pass at the door.",
    caption: "Conference · English",
    group: "corporate",
    type: "corporate",
    tradition: "corporate",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "slate",
    crest: "",
    frame: false,
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Kerala Product Summit", name2: "", subline: "Annual product conference", city: "Kochi", venue: "Convention Centre", address: "Marine Drive, Kochi", story: "A day of talks, demos and conversations with the people building products.", date: "2026-12-04", tickets: true },
  },
  {
    key: "baptism",
    name: "Sage baptism",
    blurb: "A watercolour sage sky, leaves and a small cross, with script names. For a baptism or christening.",
    caption: "Baptism · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "mist",
    crest: "✝",
    headline: "invite you to the baptism of",
    eyebrow: "Please join us",
    scheduleTitles: ["Baptism", "Reception"],
    frame: true,
    background: "mist",
    ornament: "leaves",
    sample: { name1: "Noah", name2: "", subline: "Baptism", city: "Kottayam", venue: "St. Mary's Church", address: "Kanjikuzhy, Kottayam", story: "We would be so happy to have you with us as Noah is welcomed into the church.", date: "2027-01-24" },
  },
  {
    key: "christening-blue",
    name: "Blue christening",
    blurb: "Soft lagoon blue with brass and a floral sprig, for a christening.",
    caption: "Christening · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "lagoon",
    crest: "✝",
    headline: "invite you to the christening of",
    eyebrow: "With thanksgiving",
    scheduleTitles: ["Christening", "Lunch"],
    frame: true,
    background: "sage",
    ornament: "floral",
    sample: { name1: "Liam", name2: "", subline: "Christening", city: "Bengaluru", venue: "Holy Trinity Church", address: "MG Road, Bengaluru", story: "A morning of blessings, followed by lunch with family.", date: "2027-02-14" },
  },
  {
    key: "first-communion",
    name: "Cathedral communion",
    blurb: "Ivory and navy under a cusped arch. For a First Holy Communion.",
    caption: "First Communion · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "cathedral",
    crest: "✝",
    headline: "invite you to celebrate the First Holy Communion of",
    scheduleTitles: ["Holy Mass", "Family lunch"],
    frame: true,
    ornament: "arch",
    sample: { name1: "Sophia", name2: "", subline: "First Holy Communion", city: "Chennai", venue: "St. Thomas Church", address: "Mylapore, Chennai", story: "Please join us as she receives the Eucharist for the first time.", date: "2027-05-08" },
  },
  {
    key: "naming-ceremony",
    name: "Marigold naming",
    blurb: "Saffron with a marigold garland. For a naming ceremony (Namakaran).",
    caption: "Naming ceremony · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "saffron",
    crest: "ॐ",
    headline: "invite you to the naming ceremony of",
    eyebrow: "Blessings",
    scheduleTitles: ["Namakaran", "Lunch"],
    frame: true,
    background: "blush",
    ornament: "garland",
    sample: { name1: "Baby Arya", name2: "", subline: "Namakaran", city: "Pune", venue: "Our home", address: "Kothrud, Pune", story: "Come and bless our little one as she is given her name.", date: "2027-03-07" },
  },
  {
    key: "annaprashan",
    name: "Terracotta first rice",
    blurb: "Warm terracotta and lanterns, for the first-rice ceremony (Annaprashan).",
    caption: "Annaprashan · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "terracotta",
    crest: "ॐ",
    headline: "invite you to the first rice ceremony of",
    scheduleTitles: ["Annaprashan", "Lunch"],
    frame: true,
    ornament: "lanterns",
    sample: { name1: "Ishaan", name2: "", subline: "Annaprashan", city: "Kolkata", venue: "Our home", address: "Salt Lake, Kolkata", story: "His first taste of rice, and a table full of family.", date: "2027-02-21" },
  },
  {
    key: "aqiqah",
    name: "Emerald aqiqah",
    blurb: "Emerald and gold under an arch, with the Bismillah. For an Aqiqah.",
    caption: "Aqiqah · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Dubai",
    preset: "emerald",
    crest: "بسم الله",
    headline: "invite you to the Aqiqah of",
    eyebrow: "In the name of Allah",
    scheduleTitles: ["Aqiqah", "Feast"],
    frame: true,
    ornament: "arch",
    sample: { name1: "Yusuf", name2: "", subline: "Aqiqah", city: "Dubai", venue: "Community Hall", address: "Al Barsha, Dubai", story: "Join us in gratitude for the blessing of our son.", date: "2027-03-27" },
  },
  {
    key: "bar-mitzvah",
    name: "Midnight mitzvah",
    blurb: "Midnight blue and silver with a Star of David under an arch. For a Bar or Bat Mitzvah.",
    caption: "Bar Mitzvah · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "monsoon",
    crest: "✡",
    headline: "invite you to celebrate the Bar Mitzvah of",
    scheduleTitles: ["Service", "Kiddush lunch", "Party"],
    frame: true,
    ornament: "arch",
    sample: { name1: "Daniel", name2: "", subline: "Bar Mitzvah", city: "Mumbai", venue: "Keneseth Eliyahoo", address: "Fort, Mumbai", story: "We are so proud, and we hope you will celebrate with us.", date: "2027-06-12" },
  },
  {
    key: "baby-shower",
    name: "Lavender shower",
    blurb: "A blush-to-lavender sky and a lotus. For a baby shower.",
    caption: "Baby shower · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "lavender",
    crest: "❀",
    headline: "are expecting, and you are invited to their baby shower",
    scheduleTitles: ["Baby shower"],
    frame: true,
    background: "blush",
    dateStyle: "split",
    ornament: "floral",
    sample: { name1: "Anu", name2: "", subline: "and Rahul", city: "Hyderabad", venue: "The Garden Room", address: "Banjara Hills, Hyderabad", story: "Games, blessings, and a lot of cake.", date: "2027-01-31" },
  },
  {
    key: "anniversary",
    name: "Royal anniversary",
    blurb: "Maroon and gold with a mandala. For a milestone anniversary.",
    caption: "Anniversary · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "royal",
    crest: "✦",
    headline: "invite you to celebrate their anniversary",
    scheduleTitles: ["Anniversary dinner"],
    frame: true,
    ornament: "mandala",
    sample: { name1: "Suresh", name2: "Lakshmi", subline: "twenty five years", city: "Kochi", venue: "Grand Ballroom", address: "Marine Drive, Kochi", story: "Twenty five years, and we would like you at the table.", date: "2027-02-13" },
  },
  {
    key: "graduation",
    name: "Graduate",
    blurb: "Restrained slate. For a graduation or a farewell.",
    caption: "Graduation · English",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "slate",
    crest: "✦",
    headline: "is graduating, and you are invited to celebrate",
    scheduleTitles: ["Graduation party"],
    frame: false,
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Aditi", name2: "", subline: "Class of 2027", city: "Delhi", venue: "The Terrace", address: "Hauz Khas, Delhi", story: "Four years, one degree, and a very large dinner.", date: "2027-06-20" },
  },
  {
    key: "moonlight",
    name: "Moonlight",
    blurb: "A deep blue night. Stars twinkle, the moon rises and clouds drift past.",
    caption: "Wedding · Animated night",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "nightsky",
    crest: "✦",
    frame: false,
    scene: "moonlight",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Aarav", name2: "Ananya", city: "Kochi", venue: "Bolgatty Palace", address: "Mulavukad, Kochi", story: "Under the same moon, from two different cities. Tonight we would like you with us.", date: "2027-01-22" },
  },
  {
    key: "sunrise-journey",
    name: "Night to sunrise",
    blurb: "Opens under stars and a moon. As you scroll, the moon sets, the sky warms and the sun rises.",
    caption: "Wedding · Scroll journey",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "nightsky",
    crest: "✦",
    frame: false,
    scene: "sunrise-journey",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Aarav", name2: "Ananya", city: "Udaipur", venue: "Lake Palace Terrace", address: "Pichola, Udaipur", story: "It began at night and became morning. Scroll down to see how.", date: "2027-02-12" },
  },
  {
    key: "golden-hour",
    name: "Golden hour",
    blurb: "A warm amber sky with a low sun, drifting clouds, falling petals and birds.",
    caption: "Wedding · Animated day",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "goldenhour",
    crest: "❀",
    frame: false,
    scene: "golden-hour",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Meera", name2: "Kabir", city: "Goa", venue: "Beachfront Lawn", address: "Vagator, Goa", story: "We are getting married in the last hour of light, and would love you there.", date: "2027-03-06" },
  },
  {
    key: "ocean-dusk",
    name: "Ocean dusk",
    blurb: "A sunset over the sea with rolling waves, a low sun and birds crossing.",
    caption: "Wedding · Animated sea",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "oceandusk",
    crest: "✦",
    frame: false,
    scene: "ocean-dusk",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Ishita", name2: "Rohan", city: "Alibaug", venue: "Sea Pavilion", address: "Kihim Beach, Alibaug", story: "Sea, sunset and everyone we love. That is the whole plan.", date: "2027-04-03" },
  },
  {
    key: "gold-mandala",
    name: "Gold on teal",
    blurb: "A hand-painted gold mandala on deep teal, photographed. Cream and gold type.",
    caption: "Wedding · Photo background",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "en",
    timezone: "Asia/Dubai",
    preset: "emerald",
    crest: "بسم الله",
    frame: true,
    photo: "blue-gold",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Amina", name2: "Yusuf", city: "Dubai", venue: "Al Habtoor Palace", address: "Business Bay, Dubai", story: "With the blessings of our families, we invite you to celebrate our nikah.", date: "2027-03-06" },
  },
  {
    key: "dried-flowers",
    name: "Dried flowers",
    blurb: "Dried flowers and torn paper on pale stone. Soft, quiet and modern.",
    caption: "Wedding · Photo background",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Europe/London",
    preset: "wild",
    crest: "",
    frame: false,
    photo: "white-paper",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Maya", name2: "Tom", city: "London", venue: "The Orangery", address: "Holland Park, London", story: "A small wedding, a long table and everyone we love.", date: "2027-05-09" },
  },
  {
    key: "rose-marble",
    name: "Rose marble",
    blurb: "Pink roses on white marble, for an engagement or a wedding.",
    caption: "Wedding · Photo background",
    group: "wedding",
    type: "wedding",
    tradition: "christian",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "rose",
    crest: "❀",
    frame: true,
    photo: "pink-roses",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Sara", name2: "Neil", city: "Bengaluru", venue: "The Leela Palace", address: "Old Airport Road, Bengaluru", story: "He asked, she said yes, and now we would like you there.", date: "2027-01-30" },
  },
  {
    key: "green-leaf",
    name: "Green leaf",
    blurb: "Paper on fresh green leaves. Calm and natural.",
    caption: "Wedding · Photo background",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "sage",
    crest: "",
    frame: false,
    photo: "green-leaves",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Anika", name2: "Dev", city: "Coorg", venue: "The Estate", address: "Madikeri, Coorg", story: "In the middle of the trees, with the people we love.", date: "2027-02-20" },
  },
  {
    key: "botanical-card",
    name: "Botanical card",
    blurb: "Pressed botanicals on paper, with script names.",
    caption: "Wedding · Photo background",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "wild",
    crest: "",
    frame: false,
    photo: "botanical-paper",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Richard", name2: "Amanda", city: "Kochi", venue: "The Garden Terrace", address: "Fort Kochi", story: "Two families and a garden.", date: "2027-10-20" },
  },
  {
    key: "aqua-watercolor",
    name: "Aqua watercolour",
    blurb: "Soft aqua washes with white gaps, a big pale ampersand and script names.",
    caption: "Wedding · Watercolour",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "aquawash",
    crest: "",
    frame: false,
    watercolor: "aqua",
    bigAmpersand: true,
    titleStyle: "stacked",
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "Amy", name2: "David", city: "Kochi", venue: "The Garden Terrace", address: "Fort Kochi", story: "We are getting married, and we would love you to be there.", date: "2027-08-26" },
  },
  {
    key: "rose-watercolor",
    name: "Rose watercolour",
    blurb: "Blush and rose washes, a large soft ampersand, warm grey type.",
    caption: "Wedding · Watercolour",
    group: "wedding",
    type: "wedding",
    tradition: "christian",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "rosewash",
    crest: "❀",
    frame: false,
    watercolor: "rose",
    bigAmpersand: true,
    titleStyle: "stacked",
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "Sara", name2: "Neil", city: "Bengaluru", venue: "The Leela Palace", address: "Old Airport Road, Bengaluru", story: "Two families, one garden and a long lunch.", date: "2027-01-30" },
  },
  {
    key: "lilac-watercolor",
    name: "Lilac watercolour",
    blurb: "Lilac washes for an engagement or a wedding.",
    caption: "Engagement · Watercolour",
    group: "engagement",
    type: "engagement",
    tradition: "",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "lilacwash",
    crest: "",
    frame: false,
    watercolor: "lilac",
    bigAmpersand: true,
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Anika", name2: "Dev", city: "Mumbai", venue: "The Terrace", address: "Bandra, Mumbai", story: "He asked, she said yes.", date: "2027-02-14" },
  },
  {
    key: "sage-watercolor",
    name: "Sage watercolour",
    blurb: "Sage green washes, quiet and natural.",
    caption: "Wedding · Watercolour",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "aquawash",
    crest: "",
    frame: false,
    watercolor: "sage",
    bigAmpersand: true,
    titleStyle: "stacked",
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "Maya", name2: "Tom", city: "London", venue: "The Orangery", address: "Holland Park, London", story: "A small wedding and a long table.", date: "2027-05-09" },
  },
  {
    key: "gold-watercolor",
    name: "Gold watercolour",
    blurb: "Warm gold washes with cream and grey. For a baptism or naming ceremony.",
    caption: "Baptism · Watercolour",
    group: "celebration",
    type: "birthday",
    tradition: "birthday",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "wild",
    crest: "✝",
    frame: false,
    watercolor: "gold",
    bigAmpersand: true,
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Noah", name2: "", subline: "Baptism", city: "Kottayam", venue: "St. Mary's Church", address: "Kanjikuzhy, Kottayam", story: "Please join us as Noah is welcomed.", date: "2027-01-24" },
  },
  {
    key: "site-leaf",
    name: "Wedding website: Leaf",
    blurb: "A full-width photo hero, then story, hotels, schedule, travel, Q & A and the wedding party. Fresh green.",
    caption: "Wedding website",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "sage",
    crest: "",
    frame: false,
    layout: "website",
    photo: "green-leaves",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Sneha", name2: "George", city: "Kochi", venue: "St Francis Xavier Church", address: "Kaloor, Ernakulam", story: "The first time I saw him, we were both waiting at the same gate. A few months later he sent a message, and it felt like nothing had changed.", date: "2027-01-03" },
  },
  {
    key: "site-rose",
    name: "Wedding website: Rose",
    blurb: "The same website layout in soft rose and cream, with a rose photograph at the top.",
    caption: "Wedding website",
    group: "wedding",
    type: "wedding",
    tradition: "christian",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "rose",
    crest: "",
    frame: false,
    layout: "website",
    photo: "pink-roses",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Sara", name2: "Neil", city: "Bengaluru", venue: "The Leela Palace", address: "Old Airport Road, Bengaluru", story: "We met on a train, argued about the window seat, and have been sharing it since.", date: "2027-01-30" },
  },
  {
    key: "site-stone",
    name: "Wedding website: Stone",
    blurb: "Dried flowers on pale stone. A quiet, modern website.",
    caption: "Wedding website",
    group: "wedding",
    type: "wedding",
    tradition: "civil",
    language: "en",
    timezone: "Europe/London",
    preset: "wild",
    crest: "",
    frame: false,
    layout: "website",
    photo: "white-paper",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Maya", name2: "Tom", city: "London", venue: "The Orangery", address: "Holland Park, London", story: "We would like to tell you how it began.", date: "2027-05-09" },
  },
  {
    key: "site-teal",
    name: "Wedding website: Teal",
    blurb: "Deep teal and gold, with the gold mandala photograph at the top.",
    caption: "Wedding website",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "en",
    timezone: "Asia/Dubai",
    preset: "emerald",
    crest: "",
    frame: false,
    layout: "website",
    photo: "blue-gold",
    dateStyle: "stacked",
    ornament: "none",
    sample: { name1: "Amina", name2: "Yusuf", city: "Dubai", venue: "Al Habtoor Palace", address: "Business Bay, Dubai", story: "With the blessings of both our families, we would love you to be part of our day.", date: "2027-03-06" },
  },
  {
    key: "sikh-saffron",
    name: "Saffron Anand Karaj",
    blurb: "Saffron and cream with paisley and a soft blush sky, in Punjabi.",
    caption: "Anand Karaj · Punjabi",
    group: "wedding",
    type: "wedding",
    tradition: "sikh",
    language: "pa",
    timezone: "Asia/Kolkata",
    preset: "saffron",
    crest: "ੴ",
    frame: true,
    background: "blush",
    dateStyle: "split",
    ornament: "paisley",
    sample: { name1: "ਗੁਰਪ੍ਰੀਤ", name2: "ਮਨਪ੍ਰੀਤ", city: "Ludhiana", venue: "Gurdwara Sahib", address: "Model Town, Ludhiana", story: "ਵਾਹਿਗੁਰੂ ਜੀ ਦੀ ਕਿਰਪਾ ਨਾਲ ਅਸੀਂ ਆਪਣੀ ਨਵੀਂ ਜ਼ਿੰਦਗੀ ਸ਼ੁਰੂ ਕਰ ਰਹੇ ਹਾਂ।", date: "2027-02-06" },
  },
  {
    key: "sikh-watercolor",
    name: "Rose watercolour Anand Karaj",
    blurb: "Soft rose washes with a large pale ampersand, in Punjabi.",
    caption: "Anand Karaj · Punjabi",
    group: "wedding",
    type: "wedding",
    tradition: "sikh",
    language: "pa",
    timezone: "Asia/Kolkata",
    preset: "rosewash",
    crest: "ੴ",
    frame: false,
    watercolor: "rose",
    bigAmpersand: true,
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "ਹਰਪ੍ਰੀਤ", name2: "ਸਿਮਰਨ", city: "Amritsar", venue: "Gurdwara Sahib", address: "Ranjit Avenue, Amritsar", story: "ਤੁਹਾਡੀ ਹਾਜ਼ਰੀ ਸਾਡੇ ਲਈ ਖ਼ੁਸ਼ੀ ਦੀ ਗੱਲ ਹੋਵੇਗੀ।", date: "2027-03-13" },
  },
  {
    key: "jewish-moonlight",
    name: "Moonlit chuppah",
    blurb: "A night sky with a rising moon and a Star of David, in Hebrew.",
    caption: "Jewish wedding · Hebrew",
    group: "wedding",
    type: "wedding",
    tradition: "jewish",
    language: "he",
    timezone: "Asia/Jerusalem",
    preset: "nightsky",
    crest: "✡",
    frame: false,
    scene: "moonlight",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "נועה", name2: "איתן", city: "Tel Aviv", venue: "Garden Terrace", address: "Rothschild Boulevard, Tel Aviv", story: "בעזרת ה׳ אנו מתחתנים.", date: "2027-06-10" },
  },
  {
    key: "jewish-lilac",
    name: "Lilac wash",
    blurb: "Lilac watercolour with a large soft ampersand, in Hebrew.",
    caption: "Jewish wedding · Hebrew",
    group: "wedding",
    type: "wedding",
    tradition: "jewish",
    language: "he",
    timezone: "Asia/Jerusalem",
    preset: "lilacwash",
    crest: "✡",
    frame: false,
    watercolor: "lilac",
    bigAmpersand: true,
    ornament: "none",
    sample: { name1: "רות", name2: "יונתן", city: "Haifa", venue: "The Orangery", address: "Carmel, Haifa", story: "נשמח לראותכם.", date: "2027-05-27" },
  },
  {
    key: "urdu-gold",
    name: "Gold on teal",
    blurb: "A gold mandala on deep teal, laid out right-to-left in Urdu.",
    caption: "Nikah · Urdu",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "ur",
    timezone: "Asia/Karachi",
    preset: "emerald",
    crest: "بسم اللہ",
    frame: true,
    photo: "blue-gold",
    ornament: "none",
    sample: { name1: "زینب", name2: "عمر", city: "Karachi", venue: "Marquee Hall", address: "Clifton, Karachi", story: "دعاؤں کے ساتھ ہماری نئی زندگی کا آغاز۔", date: "2027-03-27" },
  },
  {
    key: "urdu-mist",
    name: "Sage mist nikah",
    blurb: "A soft green sky with leaves and a gold mark, in Urdu.",
    caption: "Nikah · Urdu",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "ur",
    timezone: "Asia/Karachi",
    preset: "mist",
    crest: "بسم اللہ",
    frame: false,
    background: "mist",
    ornament: "leaves",
    sample: { name1: "سارہ", name2: "حمزہ", city: "Lahore", venue: "Garden Hall", address: "Gulberg, Lahore", story: "آپ کی شرکت ہمارے لیے باعثِ مسرت ہوگی۔", date: "2027-04-10" },
  },
  {
    key: "arabic-mandala",
    name: "Lagoon mandala",
    blurb: "Lagoon teal and brass with a mandala, in Arabic.",
    caption: "Nikah · Arabic",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "ar",
    timezone: "Asia/Riyadh",
    preset: "lagoon",
    crest: "بسم الله",
    frame: true,
    ornament: "mandala",
    sample: { name1: "ليلى", name2: "أحمد", city: "Riyadh", venue: "Palace Hall", address: "Olaya, Riyadh", story: "بارك الله لكما وجمع بينكما في خير.", date: "2027-04-02" },
  },
  {
    key: "arabic-night",
    name: "Night to sunrise",
    blurb: "Opens under the stars; scroll and the moon sets and the sun rises. In Arabic.",
    caption: "Nikah · Arabic",
    group: "wedding",
    type: "wedding",
    tradition: "muslim",
    language: "ar",
    timezone: "Asia/Dubai",
    preset: "nightsky",
    crest: "بسم الله",
    frame: false,
    scene: "sunrise-journey",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "مريم", name2: "خالد", city: "Dubai", venue: "Desert Garden", address: "Al Qudra, Dubai", story: "يسعدنا حضوركم ومشاركتنا فرحتنا.", date: "2027-03-18" },
  },
  {
    key: "telugu-garden",
    name: "Garden mandap",
    blurb: "A mint sky, hanging flowers and a mandap, in Telugu.",
    caption: "Telugu wedding · Telugu",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "te",
    timezone: "Asia/Kolkata",
    preset: "mist",
    crest: "ॐ",
    frame: false,
    background: "mist",
    dateStyle: "split",
    ornament: "garden",
    sample: { name1: "శ్రీనివాస్", name2: "లక్ష్మి", city: "Vijayawada", venue: "Kalyana Vedika", address: "Benz Circle, Vijayawada", story: "కుటుంబ సభ్యుల ఆశీర్వాదాలతో మా వివాహం జరుగుతోంది.", date: "2027-03-05" },
  },
  {
    key: "telugu-leaf",
    name: "Green leaf",
    blurb: "Fresh green leaves behind the names, in Telugu.",
    caption: "Telugu wedding · Telugu",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "te",
    timezone: "Asia/Kolkata",
    preset: "sage",
    crest: "ॐ",
    frame: false,
    photo: "green-leaves",
    ornament: "none",
    sample: { name1: "వంశీ", name2: "ప్రియ", city: "Visakhapatnam", venue: "Beach Lawn", address: "Rushikonda, Visakhapatnam", story: "మా ఆనందంలో మీరు పాలుపంచుకోవాలని కోరుకుంటున్నాం.", date: "2027-04-16" },
  },
  {
    key: "kannada-golden",
    name: "Golden hour",
    blurb: "A warm amber sky with a low sun, birds and falling petals, in Kannada.",
    caption: "Kannada wedding · Kannada",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "kn",
    timezone: "Asia/Kolkata",
    preset: "goldenhour",
    crest: "ॐ",
    frame: false,
    scene: "golden-hour",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "ವಿಜಯ್", name2: "ಸ್ವಾತಿ", city: "Bengaluru", venue: "Palace Grounds", address: "Jayamahal, Bengaluru", story: "ಹಿರಿಯರ ಆಶೀರ್ವಾದದೊಂದಿಗೆ ನಮ್ಮ ವಿವಾಹ.", date: "2027-03-12" },
  },
  {
    key: "kannada-royal",
    name: "Royal mandala",
    blurb: "Maroon and gold with a mandala, in Kannada.",
    caption: "Kannada wedding · Kannada",
    group: "wedding",
    type: "wedding",
    tradition: "hindu",
    language: "kn",
    timezone: "Asia/Kolkata",
    preset: "royal",
    crest: "ॐ",
    frame: true,
    ornament: "mandala",
    sample: { name1: "ಕಿರಣ್", name2: "ಅನನ್ಯ", city: "Mysuru", venue: "Kalyana Mantapa", address: "Vijayanagar, Mysuru", story: "ನಮ್ಮ ಸಂತೋಷದಲ್ಲಿ ನೀವು ಭಾಗಿಯಾಗಬೇಕೆಂದು ಬಯಸುತ್ತೇವೆ.", date: "2027-04-24" },
  },
  {
    key: "tamil-gold-wash",
    name: "Gold watercolour",
    blurb: "Warm gold washes with script names, in Tamil.",
    caption: "Tamil wedding · Tamil",
    group: "wedding",
    type: "wedding",
    tradition: "hindu-tamil",
    language: "ta",
    timezone: "Asia/Kolkata",
    preset: "wild",
    crest: "ॐ",
    frame: false,
    watercolor: "gold",
    bigAmpersand: true,
    ornament: "none",
    sample: { name1: "விஜய்", name2: "காவ்யா", city: "Coimbatore", venue: "Kalyana Mandapam", address: "RS Puram, Coimbatore", story: "பெரியோர்களின் ஆசீர்வாதத்துடன் எங்கள் திருமணம்.", date: "2027-03-07" },
  },
  {
    key: "tamil-temple",
    name: "Saffron garland",
    blurb: "Saffron and cream with a marigold garland, in Tamil.",
    caption: "Tamil wedding · Tamil",
    group: "wedding",
    type: "wedding",
    tradition: "hindu-tamil",
    language: "ta",
    timezone: "Asia/Kolkata",
    preset: "saffron",
    crest: "ॐ",
    frame: true,
    ornament: "garland",
    sample: { name1: "அருண்", name2: "திவ்யா", city: "Madurai", venue: "Thirumana Mandapam", address: "Anna Nagar, Madurai", story: "எங்கள் மகிழ்ச்சியில் நீங்களும் பங்கேற்க அன்புடன் அழைக்கிறோம்.", date: "2027-04-04" },
  },
  {
    key: "kerala-garden",
    name: "Garden morning",
    blurb: "A pale morning sky with clouds, petals and birds, in Malayalam.",
    caption: "Kerala Hindu · Malayalam",
    group: "wedding",
    type: "wedding",
    tradition: "hindu-kerala",
    language: "ml",
    timezone: "Asia/Kolkata",
    preset: "goldenhour",
    crest: "",
    frame: false,
    scene: "garden-day",
    ornament: "none",
    sample: { name1: "ദിവ്യ", name2: "വിഷ്ണു", city: "Thrissur", venue: "Vadakkunnathan Hall", address: "Thekkinkadu, Thrissur", story: "മുതിർന്നവരുടെ അനുഗ്രഹത്തോടെ ഞങ്ങൾ വിവാഹിതരാകുന്നു.", date: "2027-01-31" },
  },
  {
    key: "jain-lotus",
    name: "Lotus ivory",
    blurb: "Ivory and warm brown with a lotus, in Hindi.",
    caption: "Jain wedding · Hindi",
    group: "wedding",
    type: "wedding",
    tradition: "jain",
    language: "hi",
    timezone: "Asia/Kolkata",
    preset: "wild",
    crest: "",
    frame: true,
    ornament: "floral",
    sample: { name1: "रोहित", name2: "आरती", city: "Jaipur", venue: "Jain Bhawan", address: "Malviya Nagar, Jaipur", story: "भगवान महावीर के आशीर्वाद से हम विवाह बंधन में बंध रहे हैं।", date: "2027-02-18" },
  },
  {
    key: "jain-sage-wash",
    name: "Sage watercolour",
    blurb: "Soft sage washes with a large pale ampersand, in Hindi.",
    caption: "Jain wedding · Hindi",
    group: "wedding",
    type: "wedding",
    tradition: "jain",
    language: "hi",
    timezone: "Asia/Kolkata",
    preset: "aquawash",
    crest: "",
    frame: false,
    watercolor: "sage",
    bigAmpersand: true,
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "सौरभ", name2: "नेहा", city: "Ahmedabad", venue: "The Garden Hall", address: "Satellite, Ahmedabad", story: "आपकी उपस्थिति हमारे लिए सौभाग्य होगी।", date: "2027-03-21" },
  },
  {
    key: "buddhist-moon",
    name: "Moonlight",
    blurb: "A night sky with a rising moon and a Dharma wheel.",
    caption: "Buddhist wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "buddhist",
    language: "en",
    timezone: "Asia/Bangkok",
    preset: "nightsky",
    crest: "☸",
    frame: false,
    scene: "moonlight",
    dateStyle: "split",
    ornament: "none",
    sample: { name1: "Tenzin", name2: "Pema", city: "Bangkok", venue: "Temple Garden", address: "Sukhumvit, Bangkok", story: "May our marriage be filled with kindness, patience and joy.", date: "2027-04-15" },
  },
  {
    key: "buddhist-aqua",
    name: "Aqua watercolour",
    blurb: "Aqua washes and soft grey type, with a Dharma wheel.",
    caption: "Buddhist wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "buddhist",
    language: "en",
    timezone: "Asia/Colombo",
    preset: "aquawash",
    crest: "☸",
    frame: false,
    watercolor: "aqua",
    bigAmpersand: true,
    titleStyle: "stacked",
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "Nimal", name2: "Sanduni", city: "Kandy", venue: "Lake View Hall", address: "Peradeniya Road, Kandy", story: "We would be happy to share this day with you.", date: "2027-05-01" },
  },
  {
    key: "parsi-garden",
    name: "Garden leaves",
    blurb: "A soft mint sky with a leaf sprig and script names.",
    caption: "Parsi wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "parsi",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "mist",
    crest: "❀",
    frame: false,
    background: "mist",
    dateStyle: "split",
    ornament: "leaves",
    sample: { name1: "Roshan", name2: "Farah", city: "Mumbai", venue: "Cama Baug Garden", address: "Fort, Mumbai", story: "With the blessings of Ahura Mazda and our families.", date: "2027-02-13" },
  },
  {
    key: "parsi-rose",
    name: "Rose watercolour",
    blurb: "Rose washes with stacked capitals and a numeric date.",
    caption: "Parsi wedding · English",
    group: "wedding",
    type: "wedding",
    tradition: "parsi",
    language: "en",
    timezone: "Asia/Kolkata",
    preset: "rosewash",
    crest: "❀",
    frame: false,
    watercolor: "rose",
    bigAmpersand: true,
    titleStyle: "stacked",
    dateStyle: "numeric",
    ornament: "none",
    sample: { name1: "Zubin", name2: "Dinaz", city: "Pune", venue: "Parsi Club Lawn", address: "Camp, Pune", story: "Two families, one long friendship.", date: "2027-03-06" },
  },
];

export const templateByKey = (key: string) => TEMPLATES.find((t) => t.key === key);

// Local times for each ceremony of a sample: an evening before, the main event, an evening after.
function slots(count: number, date: string, tz: string): { start: string; end: string }[] {
  const day = (offset: number) => {
    const d = new Date(`${date}T12:00:00Z`);
    d.setUTCDate(d.getUTCDate() + offset);
    return d.toISOString().slice(0, 10);
  };
  const plan: [number, string, string][] =
    count === 1
      ? [[0, "11:00", "14:00"]]
      : count === 2
        ? [[0, "11:00", "13:00"], [0, "19:00", "22:00"]]
        : [[-1, "16:00", "20:00"], [0, "10:30", "13:00"], [0, "19:00", "23:00"]];
  return Array.from({ length: count }, (_, i) => {
    const [off, a, b] = plan[Math.min(i, plan.length - 1)];
    return { start: fromLocalInput(`${day(off)}T${a}`, tz), end: fromLocalInput(`${day(off)}T${b}`, tz) };
  });
}

// The design of a template applied on top of a fresh config. Used both for the live sample
// and for a real invitation the host starts from this template.
function applyDesign(t: Template, cfg: InviteConfig): InviteConfig {
  const p = PRESETS[t.preset];
  cfg.theme = { preset: t.preset, colors: { ...p.colors }, fonts: p.fonts, fireflies: p.fireflies, frame: t.frame, ornament: t.ornament, background: t.background ?? "flat", dateStyle: t.dateStyle ?? "stacked", titleStyle: t.titleStyle ?? "default", scene: t.scene ?? "none", photo: t.photo ?? "none", watercolor: t.watercolor ?? "none", bigAmpersand: t.bigAmpersand ?? false, layout: t.layout ?? "invitation" };
  cfg.texts.crest = t.crest;
  return cfg;
}

// A real starting point: the template's design and wording, the host's own names, no sample details.
export function starterFromTemplate(t: Template, name1: string, name2: string): InviteConfig {
  const cfg = applyDesign(t, defaultConfig(t.type, name1, name2, { tradition: t.tradition || undefined, language: t.language, timezone: t.timezone }));
  if (t.headline) cfg.event.headline = t.headline;
  if (t.eyebrow) cfg.texts.eyebrow = t.eyebrow;
  if (t.scheduleTitles?.length) cfg.schedule = t.scheduleTitles.map((title, i) => ({ key: `c${i}`, title, start: "", end: "", place: "", dress: "", note: "" }));
  return cfg;
}

// A filled-in example, so the template can be opened and looked at.
export function sampleFromTemplate(t: Template): InviteConfig {
  const s = t.sample;
  const cfg = starterFromTemplate(t, s.name1, s.name2);
  cfg.hosts.subline = s.subline ?? "";
  if (s.eyebrow) cfg.texts.eyebrow = s.eyebrow;
  cfg.event.city = s.city;
  const times = slots(cfg.schedule.length, s.date, t.timezone);
  cfg.schedule = cfg.schedule.map((e, i) => ({ ...e, ...times[i], place: e.place || s.venue }));
  const main = cfg.schedule[Math.min(1, cfg.schedule.length - 1)];
  cfg.event.dateTime = main?.start ?? "";
  cfg.venue = { ...cfg.venue, name: s.venue, line1: s.address, line2: s.city, mapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${s.venue} ${s.city}`)}` };
  cfg.story = s.story;
  if (t.layout === "website") {
    cfg.extras.faq = [
      { q: "When is the RSVP deadline?", a: "Please reply a month before the wedding so we can plan the seating and the food." },
      { q: "Can I bring a guest?", a: "Please check your personal invitation link. It lists everyone invited on your reply." },
      { q: "Are children welcome?", a: "Yes, they are very welcome at every event, and there will be a play corner at the reception." },
      { q: "What will the weather be like?", a: "Warm in the day and cooler in the evening. Bring a light shawl or jacket for later." },
    ];
    cfg.extras.party = [
      { name: "Meera", role: "Sister of the bride", note: "The reason any of this got planned on time.", photo: "" },
      { name: "Karthik", role: "Brother of the groom", note: "Best man, worst dancer.", photo: "" },
      { name: "Anita", role: "Friend of the bride", note: "Has known her since she was five.", photo: "" },
      { name: "Rohan", role: "Friend of the groom", note: "Will give a speech. Sorry in advance.", photo: "" },
    ];
    cfg.extras.hotels = [
      { name: "The Grand Residency", note: "Ten minutes from the venue. Mention the wedding for the guest rate.", url: "https://example.com" },
      { name: "Lakeside Inn", note: "Quiet rooms with a garden, fifteen minutes away.", url: "https://example.com" },
      { name: "City Stay", note: "A simple, affordable option close to the station.", url: "https://example.com" },
    ];
    cfg.extras.travel = "The nearest airport is thirty minutes from the venue. We will arrange a shuttle from the airport and the main hotels on the morning of the wedding.\n\nBy train, the closest station has taxis and autos waiting outside.";
  }
  if (t.key === "church") {
    cfg.texts.verse = "Love is patient, love is kind. It always protects, always trusts, always hopes, always perseveres. Love never fails.";
    cfg.texts.verseSource = "1 Corinthians 13:4-8";
  }
  if (t.type === "wedding" || t.type === "engagement") {
    cfg.extras.chapters = [
      { title: "How we met", date: "A few years ago", text: "A small moment that neither of us expected to matter, and then it did.", photo: "" },
      { title: "The proposal", date: "One quiet evening", text: "No crowd, no fuss, just the question and a very quick yes.", photo: "" },
      { title: "Today", date: "And now", text: "Two families, one celebration, and everyone we love in the same place.", photo: "" },
    ];
    if (t.language === "en") cfg.extras.hashtag = `#${s.name1.replace(/[^\p{L}\p{N}]/gu, "")}${s.name2 ? "And" + s.name2.replace(/[^\p{L}\p{N}]/gu, "") : ""}`;
  }
  cfg.schedule = cfg.schedule.map((e, i) => ({
    ...e,
    dress: e.dress || (i === 1 ? "Traditional" : "Festive"),
    dressColors: i === 1 ? ["#c8952a", "#7b2333", "#f3ead2"] : [],
    kids: t.type === "corporate" ? "adults" : "welcome",
    contactName: "Venue desk",
    contactPhone: "+91 98765 43210",
  }));
  cfg.rsvp = { ...cfg.rsvp, whatsapp: "919876543210", tickets: !!s.tickets };
  cfg.music = { ...cfg.music, source: "synth" };
  return cfg;
}

// Which faith or tradition family a template belongs to, for the gallery filter.
const FAITH_OF: Record<string, string> = {
  "hindu-kerala": "Hindu", hindu: "Hindu", "hindu-tamil": "Hindu", "housewarming-hindu": "Hindu",
  muslim: "Muslim", christian: "Christian", "syrian-christian": "Christian", sikh: "Sikh",
  jain: "Jain", buddhist: "Buddhist", jewish: "Jewish", parsi: "Parsi", civil: "Non-religious",
};
export const faithOf = (t: Template) => FAITH_OF[t.tradition] ?? "Any";
export const FAITHS = ["Hindu", "Muslim", "Christian", "Sikh", "Jain", "Buddhist", "Jewish", "Parsi", "Non-religious"];

// Which visual style a template has, for the gallery's style filter.
export const STYLES = ["Watercolour", "Animated sky", "Photo", "Website", "Floral and garden", "Classic"] as const;
export function styleOf(t: Template): (typeof STYLES)[number] {
  if (t.layout === "website") return "Website";
  if (t.watercolor && t.watercolor !== "none") return "Watercolour";
  if (t.scene && t.scene !== "none") return "Animated sky";
  if (t.photo && t.photo !== "none") return "Photo";
  if (["garden", "wildflower", "floral", "leaves", "garland"].includes(t.ornament)) return "Floral and garden";
  return "Classic";
}
